### ISSUE TITLE
Make cryptsetup use batch-mode to avoid useless repetitive confirmations

### ISSUE THREAD

**Issue by ldionmarcil** [BlackArch/blackarch-installer#10]
Right now [make_luks_partition()](https://github.com/BlackArch/blackarch-installer/blob/master/blackarch-install#L789) calls cryptsetup this way:

```bash
    cryptsetup -y -v -s 512 luksFormat "${part}"
```

which will prompt the user with
```
WARNING!
========
This will overwrite data on /some/path irrevocably.

Are you sure? (Type uppercase yes):
```

This uppercase-YES confirmation is stupid and goes against all human design ever, and it should be avoided. If the user enters `yes` (lowercase), then the install goes on with errors throwing left and right, leaving the user utterly confused. Since this confirmation is from `cryptsetup`, and that two prior confirmations are prompted during the installing process, I suggest we use `--batch-mode` to the cryptsetup command and skip the confirmation altogether. This way, users wont get stuck in the installer.

**Comment by noptrix** [comment]
perfect, thanks. will be included.

**Comment by noptrix** [comment]
done in version 0.3.2
