### ISSUE TITLE
Formatting erasses entire sd* regardless of chosen partitions

### ISSUE THREAD

**Issue by mgood7123** [BlackArch/blackarch-installer#13]
Formatting (or creating the required partitions) formats the entirn chosen hd dev instead of only formating the nessasary partitions created while leaving the others intact unless u specifically delete them yourself, please fix this

**Comment by bounteous17** [comment]
This will be fixed in the next version

**Comment by noptrix** [comment]
@bounteous can you open a pull-request please so i can merge in your patch?

**Comment by mgood7123** [comment]
Never mind, either change cfdisk to "cfdisk" (without the -Z) or add a
choice for users wich tells them if they want to start with a blank
partition or keep there current partition layout

**Comment by mgood7123** [comment]
Or optionally export to table via fdisk /dev/(chosen partition) > uppercase
o > temppart (or whatever u want the table to be named) wich will then be
loaded into cfdisk if users accidentally do cfdisk -Z, also could u like
add a method of telling the system to force the internal hard drive or ssd
to be mounted at sda? (As i cannot mount it at sda (wich causes trouble
with the installation as your script seems to be hardcodded to sda*) unless
i plug a second external storage device in)

**Comment by mgood7123** [comment]
Also is it possible to fix the LUKS partition being undetectable by
grub-mkconfig (if u have not installed blackarch as your first linux as it
is config is needed in order to boot) and yes i tried manually adding the
lines but i got this (inserted attachment/photo), also could u fix your
desktops so that they are fully compatible with nomodeset (and at least
make some sort of short cut popup open upon swiching or re opening a
desktop as it is difficult to know what shortcuts and combinations exist
for what desktops), also i3 (i think) does not seem to have the ability to
return to the main menu as it gives an error when u try or it has no right
click popup menu

**Comment by mgood7123** [comment]
(Basically both are indicated as not found even tho they exist on second
linux partition, probably because /dev is empty as u will not be able to
boot in to it without the grub it installs with, for now the only way (wich
leaves partitions intact but must have at least 2 primary partitions free)
is installing windows (wich is as far as i am aware of the only known
method of clearing the mbr without erasing all partitions)

**Comment by mgood7123** [comment]
Also spectrwm desktop freezes when i log into it on nomodeset (can still
move cursor but cannot interact in any way possible)

**Comment by noptrix** [comment]
this has been fixed with version https://github.com/BlackArch/blackarch-installer/releases/tag/v0.3.5 thanks to @bounteous
