### ISSUE TITLE
LUKS partition can't be found after install

### ISSUE THREAD

**Issue by CompSciMaj13** [BlackArch/blackarch-installer#18]
When I encrypt the root partition with LUKS, the grub cryptdevice is set to the partition name `/dev/sdXY`. Because I have multiple drives on my computer, the order changes from when booted into the live-iso to when I reboot after install. This causes the LUKS partition not to be found. 

This is solved (I've already tested the fix) by using `lsblk -o UUID /dev/sdXY` and setting the cryptdevice to use the partition's UUID. Its better to use persistent naming anyways. ;)

**Comment by noptrix** [comment]
thanks. this will be tested and released :)

**Comment by noptrix** [comment]
added in new release 0.5.1
