### ISSUE TITLE
WTF! Live ISO Mode with Netinstall?

### ISSUE THREAD

**Issue by WebJ0K3R** [BlackArch/blackarch-installer#21]
live boot successful, but blackarch-install not proceeding further for installation
error comes up as "WTF! Live ISO Mode with Netinstall?Nope, sorry! "

**Comment by noptrix** [comment]
@aj454565 yes, this is a bug, please update the installer: pacman -Syy and then pacman -S blackarch-installer

**Comment by WebJ0K3R** [comment]
yeah !! did it..thank u noptrix
