### ISSUE TITLE
User Account creation

### ISSUE THREAD

**Issue by CodeGuro** [BlackArch/blackarch-installer#23]
Using the BlackArch NetInstaller, version 0.6.2
There comes a point during the install process that the shell requests the client if they want to create a non-root user account, and when selected 'yes', asks for the name/password/confirmpassword. If the password and the confirm password don't match, it just notifies the client and resumes without re-prompting.

**Comment by PedroSFreitas** [comment]
@CodeGuro 
We'll check that. Thanks for reporting.

**Comment by noptrix** [comment]
@CodeGuro thanks. this should be fixed now with version 0.7. https://github.com/BlackArch/blackarch-installer/commit/66ed62caace126939ee481d0e0e8712903568631 - will be released on the 1st of june.
