### ISSUE TITLE
NetInstaller does not install BlackArch tools

### ISSUE THREAD

**Issue by CodeGuro** [BlackArch/blackarch-installer#24]
The NetInstaller does not install BlackArch tools. Shortly after the account-creation, the NetInstaller asks if it wants BlackArch tools to install, and when selecting 'yes' the client receives a notification saying it may take hours using blackman. It then says 'game over', or something along those lines, and aborts the installation process. It boots just fine, but no tools get installed.

Are there workarounds to this? I'm glad to see the WindowManagers issue fixed but it seems installer v0.6.2 has a whole other can of issues.

**Comment by CodeGuro** [comment]
Edit: This seems to be an issue only when selecting option 3: install with Blackman

**Comment by ikstream** [comment]
Blackman haven't got a lot attention lately, probably we should remove the option until blackman is fit for duty again.

**Comment by PedroSFreitas** [comment]
@CodeGuro @ikstream 
I'll take a look at Blackman by next week or so.

**Comment by PedroSFreitas** [comment]
@CodeGuro `blackman` has been updated to address one particular issue and small improvements. I strong believe you should have no problem by using it right now (:crossed_fingers:).

Although it would be great if you could provide further information of the installation log. That way we could narrow down the problem you had and to see if the `blackman`  update will address it.
