### ISSUE TITLE
Virtualbox Installation Error

### ISSUE THREAD

**Issue by JannisKirschner** [BlackArch/blackarch-installer#26]
I tried to install blackarch multiple times with different settings (partition tables, partitions, virtualbox tools...). Everytime blackarch says the installation was successful but when trying to start the virtual machine it crashes and virtualbox outputs a "severe error" message. 
Here is the log: https://pastebin.com/tNfMsqTc

**Comment by PedroSFreitas** [comment]
@JannisKirschner 
I suggest you to describe all the step you made, your VirtualBox version, the ISO version of Blackarch you used and anything else that you find useful.
Throwing a log file with ~4K lines isn't helpful.

**Comment by ikstream** [comment]
If you want to use black arch in virtual box, you could also checkout [`black arch virtualization with vagrant`](https://github.com/BlackArch/blackarch-virtualization).
It would be great if you could provide more information anyways, to improve black arch.
