### ISSUE TITLE
installer redesign

### ISSUE THREAD

**Issue by ikstream** [BlackArch/blackarch-installer#27]
Hi guys,

I would like to do a little redesign of the installer with dialog. I already changed two steps for demonstration
![snip_2018-03-05-10 43 05](https://user-images.githubusercontent.com/5787845/37018777-ea2c15fe-2115-11e8-9b61-30b765179a51.jpg)
![snip_2018-03-05-10 47 32](https://user-images.githubusercontent.com/5787845/37018786-f3c819fa-2115-11e8-8b4e-0d9c2325e87e.jpg)
(BlackArch color scheme needs to be applied)

This would allow to address some TODOs like a back button and restarting the installer, as well as fixing issues like https://github.com/BlackArch/blackarch-installer/issues/23.
Development will be done at https://github.com/ikstream/blackarch-installer/tree/ng-installer and a pull request opened, when it is done.

Before putting significant work into it, i would like some feedback from you on this. So, whats your opinion?

**Comment by PedroSFreitas** [comment]
I think it's a great idea. :+1:

**Comment by ikstream** [comment]
@PedroSFreitas I haven't used IRC in a while, but will see, that i get it up running again and join the channel

**Comment by noptrix** [comment]
@ikstream very nice. sorry for the delay... is there any chance to discuss this shortly on IRC?

**Comment by ikstream** [comment]
@noptrix Yes, there is a chance. I joined the channel a few days ago

**Comment by noptrix** [comment]
as i discussed in personal with @ikstream this is abadoned now. maybe in the future we can offer a new installer with dialog/gui
