### ISSUE TITLE
Black Arch ISO all things systemd failure

### ISSUE THREAD

**Issue by Alberto-Safra** [BlackArch/blackarch-installer#29]
Hey, 
Was excited to put BA on the new computer I just built but unfortunately after dding the iso onto my usb and booting up the computer (nomodeset) my bootup feed shows some Failed processes:
[Failed] to create volitile files and directories
[Failed] to start create system users
[Failed] to load kernals modules 
It then hangs at reached target interface

After alt arrowing to another tty and logging in (which is annoying because I am out back in tty1 every second or so) 

Systemctl status systemd-modules-load.service 
Tells me failure to find efivars. However I can ls them and see them no problem. And I have csm disabled as well. 

Please advise

**Comment by noptrix** [comment]
@Alberto-Safra thank you. all the things you mentioned are fixed now with the new version. we will release the new ISO and installer in about one week. closing this issue here

**Comment by noptrix** [comment]
Np. 1st of June everything will be released
