### ISSUE TITLE
Mirror problem

### ISSUE THREAD

**Issue by sayantanHack** [BlackArch/blackarch-installer#35]
Hi, here while installing Blackarch there have an issue no mirror is taken properly . Even the default mirror is also not doing the job. I have tried 2 3 mirrors none them are working .This is showing after I putting any mirror . 
![barch](https://user-images.githubusercontent.com/26269305/44248563-e928bf80-a208-11e8-947a-7eca0e7b8ab1.png)

**Comment by ikstream** [comment]
See Blackarch/blackarch#1995 for information
