### ISSUE TITLE
Repo Problem

### ISSUE THREAD

**Issue by mannagod** [BlackArch/blackarch-installer#36]
Hello, I just installed 

> curl -O https://blackarch.org/strap.sh
All went smootly, the keyring too.
but on running pacman -Syy i get this output>

`error: failed retrieving file 'blackarch.db' from www.mirrorservice.org : The requested URL returned error: 404
error: failed retrieving file 'blackarch.db' from blackarch.pr0s3c.nl : error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
error: failed retrieving file 'blackarch.db' from blackarch.pr0s3c.nl : error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
error: failed retrieving file 'blackarch.db' from mirrors.tuxns.net : Could not resolve host: mirrors.tuxns.net
error: failed retrieving file 'blackarch.db' from mirrors.tuxns.net : Could not resolve host: mirrors.tuxns.net
error: failed retrieving file 'blackarch.db' from mirrors.tuxns.net : Protocol "rsync" not supported or disabled in libcurl
error: failed retrieving file 'blackarch.db' from mirror.math.princeton.edu : The requested URL returned error: 404
error: failed retrieving file 'blackarch.db' from mirror.math.princeton.edu : Protocol "rsync" not supported or disabled in libcurl
error: failed retrieving file 'blackarch.db' from distro.ibiblio.org : The requested URL returned error: 404
error: failed retrieving file 'blackarch.db' from distro.ibiblio.org : Server denied you to change to the given directory
error: failed retrieving file 'blackarch.db' from deadbeef.ninja : The requested URL returned error: 404
error: failed retrieving file 'blackarch.db' from mirror.team-cymru.com : The requested URL returned error: 404
error: failed retrieving file 'blackarch.db' from mirror.team-cymru.com : Server denied you to change to the given directory
error: failed retrieving file 'blackarch.db' from mirror.team-cymru.com : Protocol "rsync" not supported or disabled in libcurl
error: failed retrieving file 'blackarch.db' from mirror.oss.maxcdn.com : Empty reply from server
error: failed retrieving file 'blackarch.db' from mirror.oss.maxcdn.com : Failed to connect to mirror.oss.maxcdn.com port 21: No route to host
error: failed retrieving file 'blackarch.db' from mirror.oss.maxcdn.com : Protocol "rsync" not supported or disabled in libcurl
error: failed to update blackarch (download library error)

That is AFTER i un-commented the mirrorlist for the USin /etc/pacman.d/
BEFORE i un-commented the error was just
`error: failed retrieving file 'blackarch.db' from www.mirrorservice.org : The requested URL returned error: 404`
Thank in advance

**Comment by ikstream** [comment]
Have you checked it again?

**Comment by mannagod** [comment]
> Have you checked it again?


Yes just now checked and I get the same errors.

**Comment by mannagod** [comment]
Ok apparently this BlackArch website is old and outdated.
I have resolved the problem by changing the entry in the pacman.config to read:

> http://www.mirrorservice.org/sites/blackarch.org/blackarch/blackarch/os/x86_64/
Repo Problem resolved.
Thanks for your comment ikstream.
