### ISSUE TITLE
Installer locales and keymap

### ISSUE THREAD

**Issue by xamafe** [BlackArch/blackarch-installer#40]
Hi,

I tried to install blackarch with encrypted root. I set the keymap to "de" and used some umlaute in my pass.
After the installation I could not log in because the password was set with a us keyboardlayout.

I did some research and found:

The installer tries to determine if the loadkeys was done correctly:
449  check $? "setting keymap" "Choosing default for you: US"
After this check the keymap is set back to "us", without any notice to the user.

My request would be:
IF the user is allowed to change the layout: set it and dont set it back to us...
ELSE dont give the option to change it, or give a warning, that is is set back to us.

Regards
Xamafe

**Comment by ikstream** [comment]
@xamafe thanks for pointing out this error, should be fixed now
