### ISSUE TITLE
CFDISK Partitioning Error or like something that

### ISSUE THREAD

**Issue by Err0rXG** [BlackArch/blackarch-installer#41]
whenever i make the partition table and write the changes in **cfdisk**, after writing , if you go to the quit option, that option saying quit without changes, if u quit via that, your partition table  is not there, so after writing the partion table if press **ctrl+c** it will save the partition changes,

    blackarch-installer version 0.9.5

**Comment by ghost** [comment]
@JetPro55 you create own partition table and when installer ask you about creating partitions... What are you doing further (detailed)?

**Comment by Err0rXG** [comment]
When installer ask me to create partitions, i created them, after creation i do write, and after writing when i went for quit, it;s discard my changes,  that the problem

by the way after writing the changes  i press ctrl+c  the problem become solved
     that's the whole story

**Comment by ghost** [comment]
@JetPro55 very strange, when you do write in cfdisk, do you write 'yes'?

**Comment by ghost** [comment]
@JetPro55 fixed in current version, will be release soon.
