### ISSUE TITLE
/tmp/$PKGBUILD: permission denied

### ISSUE THREAD

**Issue by maxlandon** [BlackArch/blackarch-installer#42]
Hello,

I tried to install a blackarch tool (bluescan) for the first time with blackman, and it gives me the following errors:

--==[ blackman - BlackArch ]==--
[+] Package bluescan already installed
cp: cannot create regular file '/tmp/bluescan/PKGBUILD': Permission denied
==> ERROR: You do not have write permission for the directory $BUILDDIR (/tmp/bluescan).
    Aborting...
[!] WARNING: Something wrong with makepkg: bluescan
[sudo] password for para:
loading packages...
error: '*.xz': could not find or read package
rm: cannot remove '/tmp/bluescan/PKGBUILD': Permission denied
 
To be noted: I ran the install twice (with the same failures), so that may explain the "Package already installed". 
I tried to look in the blackarch scripts but couldn't find the origin of the issue.

Might be related: My blackarch dir is not IN the haxx directory, but in the same directory than haxx (.blackman/blackarch & .blackman/haxx).
This is because I initialized blackarch before blackman I guess, or I did it when being in the wrong directory...
Thanks for your help !

**Comment by Edu4rdSHL** [comment]
Don't use blackman to install packages, it need to be rewrited.
