### ISSUE TITLE
Installation "failed"

### ISSUE THREAD

**Issue by g0rbe** [BlackArch/blackarch-installer#43]
I want to install BlackArch, i installed it on many device many time, but today, installer failed.
I want to install on an Acer laptop, i didn't see any error while installer runing, after reboot all of the package in `setup_extra_packages()` are missing.
Using the newest (1.0.5-1) installer.

The only solution is the old installer (0.7-1) from the previous ISO.

Sorry, i can't copy any error message here

**Comment by ghost** [comment]
@g0rbe can you confirm error now?

**Comment by g0rbe** [comment]
Works like a charm, thank you :)
