### ISSUE TITLE
Missing terminal emulator 

### ISSUE THREAD

**Issue by g0rbe** [BlackArch/blackarch-installer#44]
Install:
- online
- only i3wm
- install every blackarch tool

Problem:
- `i3-sensible-teminal` failed to start, can't find any terminal emulator, `xterm` and `gnome-terminal` was missing
- unable to find the default BlackArch wallpaper

Tried to install twice with the same result. The only solution was the offline install.

**Comment by ghost** [comment]
@g0rbe `xterm` must be present in BlackArch installation.
Installation of extra packages takes place successfully?

**Comment by g0rbe** [comment]
Sorry for the late reply.

Yes, used in verbosity mode and seems like everything is ok

**Comment by ghost** [comment]
@g0rbe can you try to install with the latest 10.0.14 version?

**Comment by g0rbe** [comment]
The problem is still available, but i found the issue.
It seems like a [known problem](https://bbs.archlinux.org/viewtopic.php?id=243210) with Alad's key.
I saw it disabled or with unknown trust. The problem is still exist after offline install.
`pacman -S archlinux-keyring` solved the issue to me after offline install.

**Comment by g0rbe** [comment]
Found a solution for my problem:
Reinitializing the keys before installing extra packages.
[solution](https://github.com/g0rbe/blackarch-installer/commit/48bb2916d9b1ee455ae55bfea1a7ff9f3d632929)

- create a reinitialize_key() function
- insert before setup_extra_packages()

Installation successful :man_dancing:

**Comment by ghost** [comment]
@g0rbe thanks a lot! Please, can you make PR for this? :)

**Comment by g0rbe** [comment]
glad to help :)
