### ISSUE TITLE
Blackarch installation on android 

### ISSUE THREAD

**Issue by Ash8991** [BlackArch/blackarch-installer#46]
Dear Sir,
Please help i want to install this in android using termux by command  
(pacman-key --init && pacman-key --populate archlinuxarm && pacman -Sy --noconfirm curl && curl -O https://blackarch.org/strap.sh && chmod +x strap.sh && ./strap.sh) 

 but it is showing no command found for pacman-key please help
and guide me for android.

**Comment by ghost** [comment]
@Ash8991 termux haven't pacman. Maybe you need [Linux Deploy](https://play.google.com/store/apps/details?id=ru.meefik.linuxdeploy) ;)
