### ISSUE TITLE
installation problems from live usb.

### ISSUE THREAD

**Issue by r3v0lut1on** [BlackArch/blackarch-installer#49]
Need. help or documentation about install from usb... Installation stops at the first menu option then drops into a terminal session. Unsure how to proceed... Installer is giving an error that says the boot device did not show back up after 30 seconds so it's falling back to an interactive prompt.

Says i can try to fix manally but i dont know what to do.

**Comment by ikstream** [comment]
Sorry for the delay, did you try to burn the live iso on the usb stick again? 
Which installation mode did you choose?
Have you tried to update the installer?
What's the exact error message?

**Comment by ikstream** [comment]
I am closing this issue, but feel free to reopen it, if this issue still exists for you
