### ISSUE TITLE
Netinstall whit problems

### ISSUE THREAD

**Issue by Kukre2005** [BlackArch/blackarch-installer#51]
Good afternoon, I wanted to warn that the installation through the netinstall is generating a kernel panic error, it is given once the installation of the blackarch is done, when the disk is booted with the system already installed, I tried it on two different computers an AMD and another Intel to rule out all kinds of incompatibility and both happened exactly the same when wanting to start the system. Removing that and what is the offline install is perfect. From now, thank you for your attention.

**Comment by noptrix** [comment]
@Kukre2005 thank you. we will check this.

**Comment by noptrix** [comment]
@Kukre2005 ok this is fixed now. please try installer v1.1.17. if still failing, re-open this issue
