### ISSUE TITLE
Netinstall vs Life-Iso

### ISSUE THREAD

**Issue by vbruhn** [BlackArch/blackarch-installer#54]
1. After a fresh install with the netinstall-medium, the normal user has sudo-rights. A very clean /etc/sudoers is written with only one line
`username ALL=(ALL) ALL`
On the Life-Iso, the file /etc/sudoers is a copy of a normal arch file. No granted privilges by default.

2. The Netinstall enables dhcpcd by default.
The Life-Iso gives the user the choice of enabling or just starting it.

Regards, Volker

**Comment by noptrix** [comment]
@vbruhn thanks for this. will be addressed soon.

**Comment by ghost** [comment]
@vbruhn done!
