### ISSUE TITLE
Problem with affter instalation blackarch

### ISSUE THREAD

**Issue by Kukre2005** [BlackArch/blackarch-installer#55]
Good I have been having problems after installing blackarch, as you can see in the photo it remains with grub, I would like to know if you can help me since I do not know how to fix this problem. Thank you
![IMG_20191010_202032](https://user-images.githubusercontent.com/46856646/66673247-8e38ff80-ec36-11e9-88c7-d1d8fb35d28e.jpg)

**Comment by leodahal4** [comment]
I have got the same problem.
Any update for the issue?
EDIT: If any solution found, Please reply me.

**Comment by ikstream** [comment]
@leodahal4 @Kukre2005  @ninjaspl0it posted a probable solution in BlackArch/blackarch#1808
can you confirm, that it works for you?

**Comment by ghost** [comment]
@Kukre2005 ping :)

**Comment by leodahal4** [comment]
That worked for Me. **Thanks**! @ikstream
