### ISSUE TITLE
Creating BOOT partition

### ISSUE THREAD

**Issue by lkaranl** [BlackArch/blackarch-installer#56]
[ - ] ERROR: Cold not create filesystem

**Comment by noraj** [comment]
Could you provide more information ?

**Comment by satias32** [comment]
Im having issues creating boot partition. 
I selected dos option 500 mb for my sda1 for the type I select efi. 90gb for my sda2 linux type. I get failed during the "hard drive setup > partition creation (boot) I tell boot partition sda1 for the format option I type fat32 root will be sda2 with the ext4 format
no swap selected.

**Comment by ikstream** [comment]
do you use `sda1` or `/dev/sda2`?

**Comment by satias32** [comment]
/dev/sda1   bootable
/dev/sda2   root

**Comment by ikstream** [comment]
Have you used the verbose option of the installer and can you please print the output of it. Also, have you updated the installer before running it?

**Comment by satias32** [comment]
Yes verbose updated installer From pacman -Sy blackarch-installer 
![IMG_20200520_094948](https://user-images.githubusercontent.com/65636530/82474652-342bd280-9a80-11ea-9c8e-6e13f07a5089.jpg)

**Comment by satias32** [comment]
![2020-05-20 09 57 16](https://user-images.githubusercontent.com/65636530/82474710-4efe4700-9a80-11ea-98ed-f04ea03a5dd1.jpg)

**Comment by satias32** [comment]
![2020-05-20 09 57 50](https://user-images.githubusercontent.com/65636530/82474769-650c0780-9a80-11ea-814c-d05e4cbe212d.jpg)

**Comment by ikstream** [comment]
Thank you,  for reporting this. I will look into it. For now you could try to do the partitioning and formatting manually with `fdisk /dev/sda` and proceed with the installation.

**Comment by satias32** [comment]
Thank you for your time. I will try.
