### ISSUE TITLE
Trouble with booteable usb, new BLACKARCH iso 2020

### ISSUE THREAD

**Issue by adrianmoris** [BlackArch/blackarch-installer#57]
Hi, help please, i have blackarch installed on my thinkpad on top (in hdd), buyed a new ssd to try install the new iso. In a terminal use this sentence "sudo dd bs=512M if=file.iso of=/dev/sdX" to create booteable usb (change file.iso for the last iso from blackarch version 2020.01.01 downloaded and X for my usb device).
Next i change the disk and try boot from usb and appear this message:

error: unknown filesystems.
Entering rescue mode...
grub rescue>

This pendrive is new and look with gparted, the filesystem created is iso9660, but not boot.
 Thanks.

**Comment by ikstream** [comment]
Could it be, that you, by accident dd'ed to your hard drive and not to your usb device?

**Comment by adrianmoris** [comment]
Thanks for the answer.
When booting press F12 and select my USB for boot.
For prove then i change SSD for HDD and try boot and the same, remove the usb and boot perfectly (HDD have old version BlackArch)

**Comment by adrianmoris** [comment]
Hello, i found a solution for me, use gdisk and 'l' for select and assign 'ef00' for make 'EFI System' partition, next use 'w' to write disk, and then booted normally and work perfectly.
I don't know why dd command it not worked at first time, if the usb was new.
I Close this.
