### ISSUE TITLE
Partitions bug

### ISSUE THREAD

**Issue by Idlefase** [BlackArch/blackarch-installer#58]
After i created  a dos table and assign it the right filesystem,size and type. The script crashes and gives a fatal saying that the partition doesn't exist or doesn't have a filesystem.

**Comment by Edu4rdSHL** [comment]
Hello. Is it still reproducible?

**Comment by Idlefase** [comment]
Possible. But ive found a way to get the system running. (Nothing special, Just switched to the live USB version since this is more usefull for me since the iptables service has been removed). 

Also there is a change that this was for a major different version of blackarch and it might got a bug fix already.

Sorry for the possible wrong issue.

Let me know if it can be closed
