### ISSUE TITLE
Error while booting blackarch 

### ISSUE THREAD

**Issue by virus212** [BlackArch/blackarch-installer#59]
Hi, I ve make a bootable USB white blackarch iso, when I boot the usb it look like if it is working infact it load the part where you can select the iso live or ram test ecc.. . But when I lunch blackarch before arriving on the login screen it restart... .
I be tried to change USB and program for make it notable but it still don't work.
Please help me !!

**Comment by noraj** [comment]
I fear what you say is not clear, we won't be able to help sorry.
Feel free to ask for re-open if you want to share more details.

**Comment by ikstream** [comment]
@virus212 are there any errors showing up during boot up?
Have you tried your stick on a different PC?
Have you briefed the iso checksum or tried to download the image again?
