### ISSUE TITLE
infinite loop formatting LUKS

### ISSUE THREAD

**Issue by drvdw** [BlackArch/blackarch-installer#60]
Because it was in an infinite loop,

on line 1042 I changed
    > $VERBOSE 2>&1 || warn 'Could not LUKS format, trying again...'; make_root_partition
to
    > $VERBOSE 2>&1 || warn 'Could not LUKS format, trying again...'

**Comment by Edu4rdSHL** [comment]
Hello, thanks for reporting, should be fixed now.
