### ISSUE TITLE
Installer is broken

### ISSUE THREAD

**Issue by bitshiftnetau** [BlackArch/blackarch-installer#63]
Just installed this to a fresh machine via netInstall iso and it simply will not boot. All I get is a flashing blinker top left hand corner of the screen. 

EDIT: I have a hunch the issue may be GPT on BIOS systems. 

Lenovo T410
BlackArch NetInstall image
Opted for an X environment

**Comment by noraj** [comment]
Go with GPT + UEFI.
https://wiki.archlinux.org/index.php/Installation_guide#Boot_the_live_environment
https://wiki.archlinux.org/index.php/Installation_guide#Verify_the_boot_mode

And as seen in https://wiki.archlinux.org/index.php/Installation_guide#Example_layouts go with GPT+UEFI and if your motherboard is very old and doesn't support UEFI go with MBR+BIOS but never mix like GPT+BIOS or MBR+UEFI.

**Comment by bitshiftnetau** [comment]
Yeh I missed the instructions where it said 'select DOS' sorry for the hastle :) 

You can actually mix GPT+BIOS, but it needs GRUB and luks1 and there needs to be other special things like a minibyte sector that never gets mounted and is set to 'BIOS Bootable'

**Comment by bitshiftnetau** [comment]
Yeh I totally forgot about that mix. Sorry for the hastle :)
