### ISSUE TITLE
Issue with graphical install Lenovo T410

### ISSUE THREAD

**Issue by bitshiftnetau** [BlackArch/blackarch-installer#64]
There seems to be a slight issue with the graphical option in the installer. I tried a few variants to see if I could nail the perpetrator: 

Black screen after decrypting drive at login, cannot get to separate tty i.e. ctrl+f3 or fN doesn't work
1. Just i3-wm 
2. "Select #6" i.e. deafult to all

Works:
1. No graphical option

I theb proceed to install i3-gaps manually and I can launch that automatically from X with no issues.

**Comment by noraj** [comment]
Can you gives more details of the issue and how it's happening please?

**Comment by bitshiftnetau** [comment]
Sorry forgot to follow up on this. @Noraj what do you mean 'more detail'? 

It was a fresh install from that date, on a Lenovo T410, I selected the above options and rebooted after install, it went to a blank screen after de-encrypting the drive. 

If I chose an install WITHOUT the graphical options, and then proceeded to manually install X and a window manager, it works.

**Comment by noraj** [comment]
- UEFI/Legacy BIOS ?
- GPT/MBR ?
- kernel LTS/vanilla ?
- hardware ?

**Comment by bitshiftnetau** [comment]
- Legacy BIOS 
- Both GPT and MBR (tried both w/ & w/o encryption)
- Whatever kernel comes with blackarch install usb, I think it's lts?

Hardware: 
Machine: Lenovo T410
CPU: Intel Core i5 M520 @2.4Ghz
Chipset: Intel 3400 series
GPU: Nvidia NVS 3100M

**Comment by ikstream** [comment]
Are you using the most recent install iso?
Do you install from the live image or using online packages?

**Comment by bitshiftnetau** [comment]
Drop it, I'm done with this project. Don't know how much more specific I can be guys. 

Fresh install as of that date. Fresh download. Fresh blackarch usb. 

Closing.

**Comment by ikstream** [comment]
That's a shame to hear.

We provide a netinstall image and a live iso, where you can choose between installing from the image or getting packages from the internet. 
This are information we need to recreate your setup as exactly as possible, especially with an error reported only by one person. Blackarch USB could mean netinstall or live iso.
