### ISSUE TITLE
1.2.12

### ISSUE THREAD

**Issue by tuxarch** [BlackArch/blackarch-installer#65]
>> Hard Drive Setup > Partition Creation (root crypto)
[+] Creating encrypted ROOT partition
/sbin/blackarch-install: line 1140: mkfs.y command not found
[-] ERROR: Could not create filesystem

**Comment by ikstream** [comment]
Which filesystem did you select for your root partition?

**Comment by ghost** [comment]
@tuxarch I suppose that you select ```y``` filesystem instead of ```ext4``` e.g.

**Comment by tuxarch** [comment]
lol, sorry
