### ISSUE TITLE
Blackarch-installer v1.2.19

### ISSUE THREAD

**Issue by Walnut-dev** [BlackArch/blackarch-installer#67]
Bug description

[+] Creating ROOT Partition
mke2fs 1.45.5 (20 march 2020)
The file 4 does not exist and no size was specified
Error: Could not create filesystem
Steps to reproduce

    Downloaded full install
    Flashed USB of 16GB

Actual result: the black arch-install script cancels
Expected result: finishing installation
Screenshots
Info for developers

Device: APPLE MB2015, issue persists on my Windows 10 aswell

Not dual booting currently however I do have 2 separate partitions saved as /dev/sdx1 and /dev/sdx2 for the macOS installation
Link to debug log

[+] Creating ROOT Partition
mke2fs 1.45.5 (20 march 2020)
The file 4 does not exist and no size was specified
Error: Could not create filesystem

**Comment by ikstream** [comment]
Let's debug here. 
Question from BlackArch/blackarch#2981 stands, what was your entered choice on root partition selection?

**Comment by Edu4rdSHL** [comment]
Closing in favor of the oldest #68.
