### ISSUE TITLE
Blackarch-installer v1.2.19

### ISSUE THREAD

**Issue by Walnut-dev** [BlackArch/blackarch-installer#68]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

[+] Creating ROOT Partition
mke2fs 1.45.5 (20 march 2020)
The file 4 does not exist and no size was specified
Error: Could not create filesystem

### Steps to reproduce

- Downloaded full install
- Flashed USB of 16GB

**Actual result:** the black arch-install script cancels
**Expected result:** finishing installation
### Info for developers

**Device:** APPLE MB2015, issue persists on my Windows 10 aswell

Not dual booting currently however I do have 2 separate partitions saved as /dev/sdx1 and /dev/sdx2 for the macOS installation

### Link to debug log

[+] Creating ROOT Partition
mke2fs 1.45.5 (20 march 2020)
The file 4 does not exist and no size was specified
Error: Could not create filesystem

**Comment by ikstream** [comment]
As there hasn't been any info provided, i am going to close this issue. Feel free to reopen and provide the info if your issue still persists
