### ISSUE TITLE
Graphical interface not working in fresh install with Intel 10th gen core.

### ISSUE THREAD

**Issue by Sable-20** [BlackArch/blackarch-installer#69]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Cannot access the login screen

I have recently installed BlackArch Linux and upon reboot everything loads(I can see all the tiny text scrolling) and then the screen turns black and does not allow me to login, of course I can access the tty shell

### Steps to reproduce

have a fresh install of Arch linux on an EFI system. Install via any option and start the OS, reboot and attempt to restart. for some reason sometimes it doesnt properly reboot ant i have to drop into the tty shell to edit some settings, not positive why, I believe it has something to do dhcpcd as once ive dropped into the tty shell I enable the dhcpcd and reboot the computer and it works

**Expected result:** 

it should obviously let me login, I dont know why but this tends to happen on fresh installs, I can pore through the kernel to find it but I think it has to do with dhcpcd and im not sure what part of it

### Info for developers

**Device:** CPU: Intel(R) i3-1005G1 CPU

no screenshots or logs since i cant access it while... well.... not being able to access the graphical interface

**Comment by Sable-20** [comment]
> Hello, you can give us logs using your TTY. You processor is a 10th gen core with a relatively new graphics card, maybe there's an issue with this. Please boot and send us the log of `journalctl -r`
> 
> ```
> journalctl -r |& curl --data-binary @- https://paste.rs
> ```

ill run it asap, just finishing up some work

**Comment by ghost** [comment]
BlackArch install
Good morning,

I have a problem with Blackarch after fresh install on New SSD. It just either locks up or it looks like a graphic card/driver issue.
Spec's of my build....
Processor...Xeon (quad core)
Ram....20Gb's
SSD...250Gb's
Grachics card...Nvidia
This is a old Dell server tower T3600 which I found new (it was never used,still in box) at a computer show and bought. And to let you know this system runs (Qubes-OS) perfectly, no issues. So I don't know why I can't run BlackArch after install.
Blackarch iso image I am using is....2020.12.01 (torrent) 15Gb

Funny from Live USB Blackarch loads and runs fine. But after installing to SSD then trying to boot it looks like it locks up after grub. I get the load screen, can either pick "Blackarch" OR "advance tools". Goes to load Blackarch and I get the start of grub and then locks up as text get all pixalated, stretched on a  black screen. Honestly looks like a grachic card/driver issue or Blackarch is failing to load something.

I have posted this also on your github..BlackArch/installer issues.

Any help would be great as I would really like to use and learn BA. Honestly I believe your BlackArch has way more many tools and functions the the other beast out there.

Thank you for your help,
B

**Comment by Edu4rdSHL** [comment]
Hello, @4dimensio. Your issue seems totally different to the one posted originally, you aren't using a 10th gen core which is the main point here. Anyways, can you please chroot into your existing installation and run the following commands:

```
pacman -Rns xf86-video-nouveau
pacman -S nvidia
mkinitcpio -P
grub-mkconfig -o /boot/grub/grub.cfg
```
then reboot and see if it works.

Regards,
Ed

**Comment by ghost** [comment]
Great I will try that thanks!
I'll let you know

**Comment by ghost** [comment]
Question, what if I update my "live usb" with
"pacman -S nvidia", then redo my install of BlackArch on the SSD?
Or is their other commands I need to use as well with 
pacman -S nvidia

This way I'll also have a current backup on usb.

**Comment by Edu4rdSHL** [comment]
That will not work probably.

**Comment by ghost** [comment]
Any ideas then? To add to live usb

**Comment by Edu4rdSHL** [comment]
Unless you make your own ISO, no. Why you don't just follow the steps I posted? That will be done in less than 5 minutes and you don't need to reinstall.

**Comment by ghost** [comment]
No I will just want a USB backup.
I will chroot into boot where grub lives and run it.

**Comment by ghost** [comment]
Thank you sir, that fixed my issue

**Comment by Edu4rdSHL** [comment]
Great, as I suspected it was Nouveau not supporting your graphics card.

**Comment by Edu4rdSHL** [comment]
@Sable-20 did you found the reason for the graphical interface not working?
