### ISSUE TITLE
ask_cfdisk() quitting on "n" does not make sense

### ISSUE THREAD

**Issue by aidanbh** [BlackArch/blackarch-installer#7]
The `ask_cfdisk()` functio currently asks the user _"Create partitions with cfdisk (root and \
boot, optional swap) [y/n]: "_ and then quits without warning on the user responding in the negative.

However, there is a perfectly sane reason to hit no here. What if I already created the partition with, say the GParted LiveDVD? Or what I prefer GNU Parted and used that before launching the installer? Even if an error message is apropos, it hardly seems appropropriate to simply quit halfway through the installation.

**Comment by noptrix** [comment]
will be changed. thanks for reporting.

**Comment by noptrix** [comment]
fixed thanks to @PedroSFreitas
