### ISSUE TITLE
Installer not detecting others Partations on hard disk

### ISSUE THREAD

**Issue by Nihal-prog** [BlackArch/blackarch-installer#72]
Hello everyone,

I was trying to dual boot my Windows pc with blackarch linux but as I was asked to make the partations with cfdisk it showed my whole (500GB) harddisk as free space, it was showing: 450GB free space while I already have 3 Partations in my harddisk where I have my windows and some personal data... I did some google searches but no luck

**Comment by ikstream** [comment]
The installer should ask for Dual Boot install, did you select it? Also please provide the installer and ISO version you used.

**Comment by Nihal-prog** [comment]
> The installer should ask for Dual Boot install, did you select it? Also please provide the installer and ISO version you used.

I am using the latest version of iso (blackarch-linux-2021.09.01-x86_64.iso) + latest installer (v1.2.22)

The installer asked me that wether I am installing it with other operating systems (windows/other os) so i entered  "y" there, one more thing I noticed that when I run cfdisk command (outside the installer) I can see all my Partations but when the cfdisk is started by the installer it treats the whole disk as free space...

**Comment by ikstream** [comment]
I will try to reproduce your issue, For now the best workaround would be to pre-create the partitions and use them during the installation process, instead of running cfdisk from the installer. Thank you for reporting.

**Comment by Nihal-prog** [comment]
> I will try to reproduce your issue, For now the best workaround would be to pre-create the partitions and use them during the installation process, instead of running cfdisk from the installer. Thank you for reporting.

Yeah I was also thinking for the same, Thank you so much for your response... 😊
