### ISSUE TITLE
BlackArch not booting after install

### ISSUE THREAD

**Issue by ghost** [BlackArch/blackarch-installer#75]
Type: Question

## Question
When I installed black arch in offline it installed successfully but when I reboot it shows there was no operating system found and again I tried in online then it shows like passwd command not found
![BF951943-452D-4902-9326-ED0552F4648A](https://user-images.githubusercontent.com/98014707/155052906-9b5c16d4-b729-4349-beda-59d1c1bb3778.jpeg)
But it shows:
![image](https://user-images.githubusercontent.com/98014707/155053026-4c2b99c0-649e-4918-a02f-9a9b74b69d95.jpg)
Sorry bro I not take the image of that passwd error but it shows in online

**Comment by ghost** [comment]
Bro I am installing in uefi

**Comment by ghost** [comment]
Bro now also same issue come in online install
![image](https://user-images.githubusercontent.com/98014707/155121955-d7205924-a9f9-4bc5-827e-a058868414ee.jpg) when I use that command

**Comment by ghost** [comment]
I use UEFI so I use gpt file system in that any issue I don’t know

**Comment by ghost** [comment]
hello

**Comment by ikstream** [comment]
Hi, i am currently unable to reproduce your issue. You might want to try the slim iso to install blackarch for now.

**Comment by ApRiP** [comment]
Same issue here.. full iso installation went fine till after reboot, shows the same 
no media found

Edit: I'm trying to do a bare metal install not vm

**Comment by ikstream** [comment]
Can you please check if any data has been written to your partitions.

**Comment by ApRiP** [comment]
Partitions have data written to them just doesn't boot without usb 
![1022035558.jpg](https://user-images.githubusercontent.com/93449402/157118366-4397e927-d525-42ac-871f-7ab1540f87c5.jpg)

**Comment by ikstream** [comment]
Did you select gpt or dos for disk label and can you please post the content of your /boot partition?

**Comment by ApRiP** [comment]
I selected gpt as a disk label and this is the contents of the partition

Edit: I'm gonna try going with dos see if that fixes my problem 

![2025301586.jpg](https://user-images.githubusercontent.com/93449402/157121928-431427a9-4a4d-44db-b4c0-2db16dc71d3e.jpg)

**Comment by ikstream** [comment]
lsblk shows you a list of available block devices and their mount points.
Could you please mount your partition, which contains /boot and run `ls /boot`

**Comment by ApRiP** [comment]
Ahaha I got it working using dos instead of gpt and also I think I need to lay off the grass a bit!! 🤣😅

**Comment by Tarunhero123** [comment]
When I firstly download blackarch I did as u r website said as blackarch-install and then it did correctly while doing that it shows a continuous msg as "passed module is unknown passed password is unchanged" error can u sove anyone reply me I can't use black arch

**Comment by ikstream** [comment]
> When I firstly download blackarch I did as u r website said as blackarch-install and then it did correctly while doing that it shows a continuous msg as "passed module is unknown passed password is unchanged" error can u sove anyone reply me I can't use black arch

Have you tried updating the keyrings, as mentioned above, before running the installer?

**Comment by Tarunhero123** [comment]
> installer

I did what is said in video of installation but showing same error as passwd module is unknown passwd password is unchanged

**Comment by Tarunhero123** [comment]
Install in offline

**Comment by ikstream** [comment]
> I did what is said in video of installation

Which video?

> but showing same error as passwd module is unknown passwd password is unchanged

Do you have any internet connection or are bound to offline?

**Comment by binva12** [comment]
> > I did what is said in video of installation
> 
> Which video?
> 
> > but showing same error as passwd module is unknown passwd password is unchanged
> 
> Do you have any internet connection or are bound to offline?

hello i have the same issue my laptop is asus zenbook ux425 i try gpt and dos but thing not worked. The installation was finish but when i reboot it not show grub boot

**Comment by Tarunhero123** [comment]
Reply to me personally

**Comment by Tarunhero123** [comment]
> unchanged
I have internet connection also

**Comment by binva12** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by ikstream** [comment]
There hasn't been any activity in more than a year. I am closing this issue
