### ISSUE TITLE
Cant see blackarch boot option after installation succeed

### ISSUE THREAD

**Issue by binva12** [BlackArch/blackarch-installer#76]
hello i have the same issue my laptop is asus zenbook ux425 i try gpt and dos but thing not worked. The installation was finish but when i reboot it not show grub boot

**Comment by binva12** [comment]
hello im now installed with blackarch linux slim edition but when im reboot it said: 
ERROR: device 'UUID=xxx' not  found. Skipping fsck.
mount: /new_root: can't find UUID=xxx.
with xxx is string of number and character
You are now being dropped into an emergency shell.
sh: can't access tty; job control turned off

**Comment by anunna** [comment]
What steps did you follow during the setup? Did you manually create your partitions?

**Comment by LeFaucheur0769** [comment]
i have the same probleme and i follow step by step blackarch-install and i have no boot image like init or wmlinuz

**Comment by binva12** [comment]
> What steps did you follow during the setup? Did you manually create your partitions?

i asked on a facebook group and I follow his steps so now i installed it. i think that because blackarch not support nvme SSD so i need to add nvme SSD to the blackarch boot usb

**Comment by noraj** [comment]
Author solved. Partitioning is manual and nvme disk are detected.

**Comment by LeFaucheur0769** [comment]
I just install the slim os and after I install all tools
