### ISSUE TITLE
Blackarch will not install 

### ISSUE THREAD

**Issue by g3ck0hacks** [BlackArch/blackarch-installer#77]
Hi there. I downloaded blackarch to install on my laptop.

I ran the installer, it installed without any errors however after rebooting the system after the install, it says "default boot device missing or boot failed"
i am unsure what to do here has it said it installed but it did not, i have tried everything.

I setup a boot partition, swap and root partition. i used dos option and chose ext4 filesystem.

Please help me

**Comment by anunna** [comment]
Did you set the boot flag when you created the boot partition?

**Comment by g3ck0hacks** [comment]
> Did you set the boot flag when you created the boot partition?

yes i did, i even tried installing to different drives and nothing worked!

**Comment by anunna** [comment]
Can you send screenshots of your partition scheme `fdisk -l /dev/sdX` and output of your `/boot` directory?

**Comment by g3ck0hacks** [comment]
> Can you send screenshots of your partition scheme `fdisk -l /dev/sdX` and output of your `/boot` directory?

yes, i am going to try install on top of arch linux and if that does not work, i will send output of those things.
Thanks :)

**Comment by g3ck0hacks** [comment]
> Can you send screenshots of your partition scheme `fdisk -l /dev/sdX` and output of your `/boot` directory?

Hi, i have managed to install the tools on top of arch linux however i can only access the tools via terminal as they will not show up in the start menu at all or when right clicking the desktop

**Comment by anunna** [comment]
We have a `blackarch-menus` package that generates this for you. However, as you can imagine, most tools are terminal based.
