### ISSUE TITLE
net-install: "chroot failed to run command passwd" loop

### ISSUE THREAD

**Issue by YonLiud** [BlackArch/blackarch-installer#79]
Latest net install ISO. The error occurs after finishing partitioning drives

**Comment by noraj** [comment]
Which error? There is not enough details to process. Feel free to add details here.

**Comment by YonLiud** [comment]
@noraj the title is the problem

```chroot failed to run command passwd```

it will spam this across the screen unless rebooted

**Comment by dualfade** [comment]
I can confirm this happens during installation. I posted about this a few weeks ago to the dev chan.
If I remember correctly it happen right before package installation.If I remember correctly this happened with the net installer.
If you guys have any other details please confirm.
Thanks~!>D------- Original Message -------

**Comment by noraj** [comment]
I tried the net installer and yet it is blocked in a loop at this stage, but if you use the verbose output you'll see there are several critical errors in previous steps but changes too quick from one screen to another to be able to read what happened.

**Comment by YonLiud** [comment]
> I tried the net installer and yet it is blocked in a loop at this stage, but if you use the verbose output you'll see there are several critical errors in previous steps but changes too quick from one screen to another to be able to read what happened.

I was unable to read the text displayed there

**Comment by Vernoxvernax** [comment]
`blackarch-installer v1.2.22`

Issue still persists. Multiple errors flashing, then passwd loop.
Something like
```
Command not found: passwd,
```

**Comment by skiss0** [comment]
> @noraj the title is the problem
> 
> `chroot failed to run command passwd`
> 
> it will spam this across the screen unless rebooted


exactly after this step, when trying to create root account

![IMG_20220819_230029](https://user-images.githubusercontent.com/39972504/185768514-4435a28e-3142-4c4b-8dc1-0fae10c89ed8.jpg)

chroot: failed to run command 'passwd': no such file or directory.

**Comment by Vernoxvernax** [comment]
> > @noraj the title is the problem
> > 
> > `chroot failed to run command passwd`
> > 
> > it will spam this across the screen unless rebooted
> 
> 
> exactly after this step, when trying to create root account
> 
> ![IMG_20220819_230029](https://user-images.githubusercontent.com/39972504/185768514-4435a28e-3142-4c4b-8dc1-0fae10c89ed8.jpg)
> 
> chroot: failed to run command 'passwd': no such file or directory.
> 

You have to run the following command, before starting the script.
```
pacman -Syy archlinux-keyring blackarch-keyring
```
If thats not sufficient, you could then try to refresh the pacman keys. See the man-pages.

**Comment by skiss0** [comment]
> > > @noraj the title is the problem
> > > `chroot failed to run command passwd`
> > > it will spam this across the screen unless rebooted
> > 
> > 
> > exactly after this step, when trying to create root account
> > ![IMG_20220819_230029](https://user-images.githubusercontent.com/39972504/185768514-4435a28e-3142-4c4b-8dc1-0fae10c89ed8.jpg)
> > chroot: failed to run command 'passwd': no such file or directory.
> 
> You have to run the following command, before starting the script.
> 
> ```
> pacman -Syy archlinux-keyring blackarch-keyring
> ```
> 
> If thats not sufficient, you could then try to refresh the pacman keys. See the man-pages.

Ok thanks
