### ISSUE TITLE
Issue regarding EFI but also cfdisk

### ISSUE THREAD

**Issue by changemenemo** [BlackArch/blackarch-installer#80]
Installation in full iso mode
Installation done on external nvme
Several installations done already on the same nvme with other linux distribution
Problem:
 Cfdisk -> not recognizing the gpt partition 

 No efi section of the installer is being triggered

I had to make the partition manually externally and now I'm fixing the efi symptom with chrooting the system and activating systems-boot as described in one other old issue. 

And before you say anything, no, the os-prober of grub is not recognizing any system on external nvme apparently. So only the EFI folder in the ESP partition is useful here.

**Comment by noraj** [comment]
>  Cfdisk -> not recognizing the gpt partition

GPT, GUID Partition Table is a partition table format (generally opposed to MBR). So a "gpt partition" means nothing. I don't understand what you mean here.

> No efi section of the installer is being triggered
>
> I had to make the partition manually externally...

You mean the installer is not offering your to install a bootloader? If you mean creating an ESP, you have to create it manually with cfdisk as for the root partition.

> And before you say anything, no, the os-prober of grub is not recognizing any system on external nvme apparently.

It may not be that but some motherboard have NVMe slots that can't be used to boot an OS but just as data storage. But what do you mean by "external nvme"? The NVMe disk is not plugged to the MB? You have a NVMe disk in an external USB case?

**Comment by changemenemo** [comment]
Well it does not work at all. Whether it's fedora or debian like distributions, they all create a specific folder in EFI folder. Not for archLinux apparently, it creates a bunch of things which does not play well with other distributions. Plus it does not get recognized correctly nor by the uefi manager from the uefi bios nor the tool rEFInd.

Note to that: it does more or less succeed to create an entry but this entry just lead to a menu with reboot to firmware utility bios so...

**Comment by noraj** [comment]
AL/BA manage EFI just well. I suggest you stop saying nonsense and complaining and start RTFM instead:

- [EFI system partition](https://wiki.archlinux.org/title/EFI_system_partition)
- [REFInd](https://wiki.archlinux.org/title/REFInd)

**Comment by noraj** [comment]
#81
