### ISSUE TITLE
Issue regarding EFI but also cfdisk Follow up

### ISSUE THREAD

**Issue by changemenemo** [BlackArch/blackarch-installer#81]
Since you didn't understand a single word of what I was saying and didn't get the fact I did the previous ticket on the fly (or I would have put some more screenshots and correct the ticket for the missing word) I'm going to rephrase.
And for the record, I'm still doing this on the fly so no need to be insulting by saying that I didn't read the fucking manual etc.

1/ cfdisk during your installer (and I emphase on yours, because during an up to date archLinux install =>so not following a script but doing the whole archlinux setup manually as described in the FM ^^) is bugging. 
A/ it does not recognize the gpt partition table of the nvme disk which we selected previously.(for a reminder, in your own doc, the selection wizard of the partition table should not appear of there is already one in place on the selected disk) 
=> B/ it forces me to select a partition table which would erase the old one which I don't want since there are other OS on that disk.
=> C/ forces me to quit cfdisk since I don't want to screw up my whole disk.

2/ you could warn the user that EFI partition are not populated the same way as debian like or fedora like distributions. And so it could cause problems by using the same ESP partition than other linux distros. So better to a new ESP partition living next to another one populated for the other distribution.

And as for the note, I was telling you for some context that I was using an external nvme ssd and if you want to know even more on a rog Asus strix enclosure. Which works perfectly fine, thanks to put that in doubt. Just cfdisk or the version of cfdisk in your full install iso is not handling it very well apparently.

Just a little friendly reminder, don't forget that I was not asking any help.
I took the time to give you some hints and context about the fact that your installer is not handling things properly in a marginal usecase(which is external ssd installation).
And yes sorry there was no technical context like screenshots ands logs but you didn't give me really the time did you? 

And Same now, I can't take the time right now because even with installing blackarch on top of arch (well some packages like the pfff one has bad signing so it's a pain in the ass) it gives me headaches.

So just next time 
1/ being less rude
2/ give Kevin a little more time especially since it is to improve the installer and not asking you for support.

Édit: 
And thank you very much but I do know how ESP works and that's' why I can tell you how it is populating usually and tell you why it should be nice to put a warning in place.

**Comment by noraj** [comment]
> because during an up to date archLinux install =>so not following a script but doing the whole archlinux setup manually as described in the FM

If you have a manually installed AL, just run `strap.sh` as explained in _Installing on top of ArchLinux_. Using a BA ISO + installer is only need for those who don't have a per-existing Arch install.

I don't understand what you are doing.

From #80 

> Well it does not work at all. Whether it's fedora or debian like distributions, they all create a specific folder in EFI folder. Not for archLinux apparently, it creates a bunch of things which does not play well with other distributions.

On ArchLinux + using rEFInd, my ESP is monted at `/efi` :

```
$ tree /efi -L 2
/efi
└── EFI
    ├── arch
    ├── refind
    └── tools
```

But it's up to you to define an [Alternative mount points](https://wiki.archlinux.org/title/EFI_system_partition#Alternative_mount_points), eg. `EFI/arch`.

> Just cfdisk or the version of cfdisk in your full install iso is not handling it very well apparently.

It's unmodified latest version of fdisk cf. https://github.com/archlinux/svntogit-packages/blob/packages/util-linux/trunk/PKGBUILD

> And Same now, I can't take the time right now because even with installing blackarch on top of arch (well some packages like the pfff one has bad signing so it's a pain in the ass) it gives me headaches.

Again complaining without giving any details and not RTFMing:

https://blackarch.org/faq.html

![image](https://user-images.githubusercontent.com/16578570/179624796-e10b9b82-e778-44f4-954a-156e99158298.png)
