### ISSUE TITLE
blackarch-install chroot: failed to run command passwd

### ISSUE THREAD

**Issue by mariaWitch** [BlackArch/blackarch-installer#85]
Currently using the most recently built netinstall iso, and am getting the same exact error as BlackArch/blackarch#2872 when trying to install even after updating the keyrings for blackarch and archlinux.

**Comment by noraj** [comment]
New ISO will be released soon.

**Comment by mariaWitch** [comment]
How soon is "soon" because you have been saying this for almost a year now.

**Comment by noraj** [comment]
The ISO is ready, it will be release 01/04/2023 as I heard of.

**Comment by ikstream** [comment]
Install from arch netinstall iso and put Blackarch on top, if you don't want to wait until the release.

**Comment by anunna** [comment]
Issue was fixed already in installer and iso

**Comment by qdii** [comment]
Ran into the same issue today with blackarch-linux-netinst-2023.04.01-x86_64.iso

**Comment by CX330Blake** [comment]
> Ran into the same issue today with blackarch-linux-netinst-2023.04.01-x86_64.iso

+1

**Comment by arortell** [comment]
Same problem today. Reinstalling the archlinux and blackarch keyring is not correcting the problem anymore. I have been trying to install for 4 hours now. No luck.
