### ISSUE TITLE
reboot restarts the netinstall

### ISSUE THREAD

**Issue by osalbahr** [BlackArch/blackarch-installer#89]
# reboot restarts the netinstall

## Issue

I followed https://blackarch.org/blackarch-install.html using BlackArch Linux 64 bit Netinstall ISO 2023.04.01 (df2dfcfafa1a8f9bab8afd9aa6b788de00e03e09). I managed to go all the way to the end, but when I reboot, I needed to do everything all over again, and the same thing happened again. How should I troubleshoot this?

## After install:

<img width="1348" alt="Screen Shot 2023-05-09 at 1 18 45 PM" src="https://github.com/BlackArch/blackarch-installer/assets/54853250/805725d6-04b0-4842-9285-a3c927cff579">

## After reboot:

<img width="708" alt="Screen Shot 2023-05-09 at 1 20 27 PM" src="https://github.com/BlackArch/blackarch-installer/assets/54853250/a078b417-7f7d-46c8-b3c0-900f9776c4a3">

**Comment by anunna** [comment]
Have you removed the ISO after installation? Chances are your disk drive boots first.

**Comment by osalbahr** [comment]
No, I haven’t tried that. Should I delete/move the iso before `reboot`ing?

**Comment by osalbahr** [comment]
Ok. This step in this guide fixes it: https://hackingpassion.com/blackarch-linux-penetration-testing-2020-01-01-complete-install/#blackarch-remove-disk-from-virtual-drive

It might be a good idea to add this step to the BlackArch guide.
