### ISSUE TITLE
Error loop on chroot "passwd: No such file or directory"

### ISSUE THREAD

**Issue by xero-lib** [BlackArch/blackarch-installer#90]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

When running the install script (after updating arch and blackarch keyrings as described [here](https://github.com/BlackArch/blackarch/issues/2872), I run into the error loop `chroot: failed to run command 'passwd': No such file or directory`
### Steps to reproduce

- Flash latest ISO from website
- Boot from flashdrive
- Connect to internet
- Update archlinux and blackarch keyrings
- Run install script
- Select full root encryption
- Format disks with 200M ext4 EFI, 16G swap, rest Linux FS 

**Actual result:** I run into the error loop `chroot: failed to run command 'passwd': No such file or directory` even after following the solution proposed [here](https://github.com/BlackArch/blackarch/issues/2872).

**Expected result:** BlackArch installs properly.

### Info for developers

**Device:** Lenovo ThinkPad

**Tool version:** blackarch-installer 1.2.24-1

### Link to debug log

Nothing appropriate.

**Comment by noraj** [comment]
Which ISO did you use? (full filename please).

**Comment by xero-lib** [comment]
> Which ISO did you use? (full filename please).

blackarch-linux-full-2023.04.01-x86_64.iso

**Comment by cr4sh-me** [comment]
I'm also experiencing the same issue with `blackarch-linux-full-2023.04.01-x86_64.iso` and `blackarch-linux-netinst-2023.04.01-x86_64.iso`

**Comment by anunna** [comment]
I just downloaded the full iso `blackarch-linux-full-2023.04.01-x86_64.iso` and installed without this problem multiple times simulating different environments. 

This issue is aged, but see #93. This has alwasy been the solution to passwd command not found and we have indroduced this fix very long time ago in `blackarch-install`.

Let us know if you still have the issue in #93 and what your exact steps are.

**Comment by cr4sh-me** [comment]
Yes, im still experiencing issue

Steps i made:

1. Flash latest ISO from website
2. Boot from flashdrive
3. Connect to internet
4. Update archlinux and blackarch keyrings (also tried without this)
5. Run install script
6. Select full root encryption
7. Select gpt label type
8. Format disks with 512M EFI SYSTEM, rest Linux FS

Device: Lenovo ThinkPad E590
