### ISSUE TITLE
INSTALLATION ISSUE " chroot: failed to run command 'passwd' : No such file or directory "

### ISSUE THREAD

**Issue by EXTER001** [BlackArch/blackarch-installer#94]
DURING THE INSTALLATION , EVERYTHING IS GOING WELL, AFTER IT DOWNLOAD SUCCEFULLY THE 160 PACKAGES THE INSTALL STOPS AND REPEATS INDEFINITELY :

" chroot: failed to run command 'passwd' : No such file or directory "

I CAN STOP IT WITH CTRL+C

**Comment by noraj** [comment]
Have you searched for and checked the similar issues first?

- https://github.com/BlackArch/blackarch/issues/3428
- https://github.com/BlackArch/blackarch/issues/3210
- https://github.com/BlackArch/blackarch-installer/issues/74
- https://github.com/BlackArch/blackarch/issues/2872
- https://github.com/BlackArch/blackarch/issues/2084

**Comment by EXTER001** [comment]
Hey all, problem solved doing this 👍 

Run pacman -Syy archlinux-keyring blackarch-keyring before Blackarch installer.

If you cannot run pacman -Syy archlinux-keyring blackarch-keyring because you don't have your network configured. Run the blackarch-install installer up until the network is configured then CTRL+C to interrupt the installer, then run the pacman command.
Install worked like a charm after that.
